version: '{build}'
image: Visual Studio 2022

build_script:
  - npm pack

artifacts:
  - path: '*.tgz'

test_script:
  - npm test
  - bash -c "npm install -g *.tgz"
  - dotnet-run test\net6.0\test.dll
