matrix:
  include:
    - os: osx
    - os: linux
      language: csharp
      mono: latest

script:
  - npm install
  - npm run test
  - npm pack --silent
  - npm install -g *.tgz
  - dotnet-run test/test.exe
